# Generated by Django 6.0.4 on 2026-05-09 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedorapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100)),
                ('aereolinea', models.CharField(max_length=100)),
                ('codigo_vuelo', models.CharField(max_length=20)),
                ('origen', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=10)),
                ('fecha_salida', models.DateTimeField()),
                ('fehca_llegada', models.DateTimeField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asientos_disponibles', models.IntegerField()),
                ('creado_en', models.DateTimeField()),
                ('Proveedor_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.proveedorapi')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_confirmacion', models.CharField(max_length=20)),
                ('fecha_transaccion', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('cantidad_pasajeros', models.IntegerField(default=1)),
                ('asiento_asignados', models.CharField(max_length=20)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('Vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.vuelo')),
            ],
        ),
    ]
