# Generated by Django 6.0.4 on 2026-05-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedorapi',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vuelo',
            options={'managed': False},
        ),
    ]
