# Generated by Django 6.0.4 on 2026-05-09 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('idioma_preferido', models.CharField(default='es', max_length=10)),
                ('moneda_preferida', models.CharField(default='MXN', max_length=10)),
                ('email_verificado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario_rol',
            fields=[
                ('id', models.AutoField(db_column='id_usuario_rol', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('token', models.CharField(max_length=100)),
                ('expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'verificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_origen', models.CharField(max_length=45)),
                ('user_agent', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
