# Generated by Django 6.0.4 on 2026-05-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'managed': False},
        ),
    ]
