# Generated by Django 6.0.4 on 2026-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_sesion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedorapi',
            fields=[
                ('id_proveedor', models.AutoField(db_column='id_proveedor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor_api',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='sesion',
            table='sesion',
        ),
    ]
